development:
  host: localhost
  database: uploader_development

test:
  host: localhost
  database: uploader_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
